// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-myPovExU9SvYTpTENI2L6lg5IJoJPY',
    appId: '1:671002649907:web:71a3b0826752643f98ca46',
    messagingSenderId: '671002649907',
    projectId: 'chatapptute-d56b4',
    authDomain: 'chatapptute-d56b4.firebaseapp.com',
    storageBucket: 'chatapptute-d56b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMS7lTgSRan7GsVXKms6IUxAqrcx38ro',
    appId: '1:671002649907:android:4d9a418198f270a998ca46',
    messagingSenderId: '671002649907',
    projectId: 'chatapptute-d56b4',
    storageBucket: 'chatapptute-d56b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Ej_K1LDbpWvHcnLuV2V6zglabfhRWWo',
    appId: '1:671002649907:ios:82b1325681b1960f98ca46',
    messagingSenderId: '671002649907',
    projectId: 'chatapptute-d56b4',
    storageBucket: 'chatapptute-d56b4.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Ej_K1LDbpWvHcnLuV2V6zglabfhRWWo',
    appId: '1:671002649907:ios:7e1339076090df1c98ca46',
    messagingSenderId: '671002649907',
    projectId: 'chatapptute-d56b4',
    storageBucket: 'chatapptute-d56b4.appspot.com',
    iosBundleId: 'com.example.loginapp.RunnerTests',
  );
}
